### PR TITLE
Resolve mhchem option clash

### PR DESCRIPTION
**Pull request by britthubs**
This fixes the option clash error. The changes also work in the devcontainer and Overleaf. Does this look okay?

### CODE REVIEW

**Comment by britthubs** [comment]
@ruvdrsti I wasn't able to add any reviewers.

**Review by emielvb — APPROVED** [review]
Able to reproduce in container without issues. LGTM.

**Comment by emielvb** [comment]
@ruvdrsti Github actions seems to be acting up. Can you look into this?

**Comment by ruvdrsti** [comment]
The reason the check fails is that the version of the action is outdated. I have changed this on the main branch of GQCG. @britthubs You can merge this PR at your convenience, it should build on github. If you want to get your local .yml file up to date, you can copy the version on the GQCG:main branch. 

Thank you for your contribution!

**Review by ruvdrsti — APPROVED** [review]

**Comment by britthubs** [comment]
I don't think I have permission to merge the PR, unless I have understood it wrong.

**Pull request merged**
